// This header defines our custom movement component for the PodVehicle.
// It handles applying movement and steering forces, and integrates with network prediction.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/PawnMovementComponent.h"
#include "PodVehicleMovementComponent.generated.h"

class APodVehicle;

// Define a struct to hold client move data for prediction and reconciliation
USTRUCT()
struct FClientMoveData
{
	GENERATED_BODY()

	// Input values
	UPROPERTY()
	float MoveForwardInput;
	UPROPERTY()
	float TurnRightInput;
	UPROPERTY()
	bool bIsBoosting;
	UPROPERTY()
	bool bIsBraking;
	UPROPERTY()
	bool bIsDrifting;

	// Unique ID for this move, used for reconciliation
	UPROPERTY()
	uint32 MoveID;

	// DeltaTime that the client used for this move's prediction
	UPROPERTY()
	float DeltaTime; 

	FClientMoveData() 
		: MoveForwardInput(0.0f), TurnRightInput(0.0f), bIsBoosting(false), bIsBraking(false), bIsDrifting(false), MoveID(0), DeltaTime(0.0f) {}
	FClientMoveData(float InForward, float InTurn, bool InBoosting, bool InBraking, bool InDrifting, uint32 InID, float InDeltaTime)
		: MoveForwardInput(InForward), TurnRightInput(InTurn), bIsBoosting(InBoosting), bIsBraking(InBraking), bIsDrifting(InDrifting), MoveID(InID), DeltaTime(InDeltaTime) {}

	// For TArray::RemoveSingle, needed to compare moves
	bool operator==(const FClientMoveData& Other) const
	{
		return MoveID == Other.MoveID;
	}
};

/**
 * Custom movement component for the PodVehicle, handling high-speed arcade physics
 * and network replication for smooth multiplayer gameplay.
 */
UCLASS()
class PROJECTPODRACER_API UPodVehicleMovementComponent : public UPawnMovementComponent
{
	GENERATED_BODY()

public:
	UPodVehicleMovementComponent();
	
	virtual void BeginPlay() override;

	// Overrides from UPawnMovementComponent
	// This is where the core movement logic for the vehicle will live.
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	// --- Input State ---
	// Stores the current desired forward movement input (e.g., from W/S keys or joystick).
	// Value is typically between -1.0 (backward) and 1.0 (forward).
	UPROPERTY(Transient, Replicated) // Transient: Not saved. Replicated: Sent over network.
	float MoveForwardInput;
	// Stores the current desired turning input (e.g., from A/D keys or joystick).
	// Value is typically between -1.0 (left) and 1.0 (right).
	UPROPERTY(Transient, Replicated)
	float TurnRightInput;
	// Is the boost button currently held?
	UPROPERTY(Transient, Replicated)
	bool bIsBoosting;
	// Is the brake button currently held?
	UPROPERTY(Transient, Replicated)
	bool bIsBraking;
	// Is the drift button currently held?
	UPROPERTY(Transient, Replicated)
	bool bIsDrifting;

	// --- Replicated Angular State ---
	// Current angular velocity around the Yaw axis. Replicated for simulated proxies.
	UPROPERTY(Transient, Replicated)
	float CurrentAngularYawVelocity;

	// Setter for MoveForwardInput, used by the owning PodVehicle.
	void SetMoveForwardInput(float Value);
	// Setter for TurnRightInput, used by the owning PodVehicle.
	void SetTurnRightInput(float Value);
	// Setter for bIsBoosting.
	void SetBoostInput(bool bNewState);
	// Setter for bIsBraking.
	void SetBrakeInput(bool bNewState);
	// Setter for bIsDrifting.
	void SetDriftInput(bool bNewState);

	// --- Server RPCs for Client Input ---
	// This RPC is called by the client to send its MoveForward input to the server.
	UFUNCTION(Server, Unreliable) // Unreliable for frequent input, client will resend if needed
	void Server_ProcessMove(FClientMoveData ClientMove);
	// No _Implementation for RPCs here, generated by UHT.

	// --- Client RPC for Server Acknowledgment ---
	// This RPC is called by the server to send authoritative state back to the owning client.
	UFUNCTION(Client, Reliable)
	void Client_AcknowledgeMove(uint32 LastProcessedMoveID, FVector ServerLocation, FRotator ServerRotation, FVector ServerVelocity);

	// --- Vehicle Physics Parameters ---
	// Maximum speed the pod can reach.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement")
	float MaxSpeed;
	// Acceleration rate of the pod.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement")
	float Acceleration;
	// Deceleration rate when no forward input is applied.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement")
	float Deceleration;
	// Rate at which the pod can turn (degrees per second).
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement")
	float TurnSpeed;
	// Amount of damping applied to linear velocity (friction/air resistance).
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement")
	float LinearDamping;
	// Amount of damping applied to angular velocity (how quickly it stops rotating).
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement")
	float AngularDamping;

	// Boost related parameters
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|Boost")
	float BoostStrength; // Additional acceleration when boosting
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|Boost")
	float BoostMaxSpeedMultiplier; // Max speed multiplier when boosting

	// Brake related parameters
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|Brake")
	float BrakeForce; // Deceleration force when braking

	// Drift related parameters
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|Drift")
	float DriftTurnSpeedMultiplier; // How much turn speed is multiplied when drifting
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|Drift")
	float DriftLinearDampingMultiplier; // How much linear damping is multiplied when drifting (less grip)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|Drift")
	float DriftAngularDampingMultiplier; // How much angular damping is multiplied when drifting (more slide)

	// Threshold for position difference before a client correction occurs (e.g., in cm)
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|Networking")
	float CorrectionThreshold;

	// Air control parameters
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|AirControl")
	float AirControlTurnFactor; // How much TurnRightInput affects Yaw when airborne
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "PodMovement|AirControl")
	float AirControlPitchFactor; // How much TurnRightInput (or MoveForwardInput) affects Pitch when airborne

	UPROPERTY()
	APodVehicle* OwningPodVehicle;

	// --- Network Replication ---
	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

protected:
	// A counter for unique move IDs for client prediction.
	uint32 CurrentMoveID;

	// History of client-side moves for reconciliation.
	TArray<FClientMoveData> ClientMoveHistory;

	// Helper function to apply movement logic for a given input.
	// This function will be called on the client for prediction and replay, and on the server for authority.
	void ApplyMovementLogic(float InMoveForwardInput, float InTurnRightInput, bool InIsBoosting, bool InIsBraking, bool InIsDrifting, float InDeltaTime, FVector& OutVelocity, FRotator& OutRotation, FVector& OutLocation, float& OutAngularYawVelocity);

	// Ground detection
	bool IsGrounded() const;
};